
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        command: /bin/bash ./entrypoint.sh
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: pasSord123
        volumes:
            - /var/opt/mssql
            - ./entrypoint.sh:/entrypoint.sh
            - ./sql:/sql